### ISSUE TITLE
Recipes repo - efs2-recipes

### ISSUE THREAD

**Issue by paul-hammant** [madflojo/efs2#12]
## Goal

An exchange for people wanting to read and contribute to Efs2file scripts that purport to do something useful that others may want to copy.

## Design

Some directory structure: 

```
components/
  nginx/
    static-content/
      Efs2file
      readme.md
  sinatra/
    hello-world/
      Efs2file
      readme.md
applications/
  plex-server
    default-setup/
      Efs2file
      readme.md
```

### Examples

The Nginx example of the main README could also exist in this directory structure.

### Unknowns

Efs2 doesn't purport to provide a language that adapts to apk/apt/rpm differences, so that might need to be codified in the file or directory naming:

```
applications/
  plex-server
    default-setup-debian8-and-lower/
      Efs2file
      readme.md
    default-setup-debian9-and-above/
      Efs2file
      readme.md
```

**Comment by madflojo** [comment]
👍  This would be similar to like the salt-formulas repo/org for Saltstack. I like it.

**Comment by paul-hammant** [comment]
Indeed - WITHOUT the super steep learning curve :)

**Comment by madflojo** [comment]
Done: https://github.com/madflojo/efs2-examples

I also updated the README and started a gh-pages for Efs2.
