### ISSUE TITLE
Rename --passwd to --passphrase maybe?

### ISSUE THREAD

**Issue by paul-hammant** [madflojo/efs2#18]
## Describe the bug

--passwd is part of the CLI. At face value it suggests that it is for the remote account's password, but it is actually for the passphrase of the SSH private key locally.

## Expected behavior

I would think this would be better as --passphrase or --pki-passphrase

**Comment by madflojo** [comment]
So --passwd is actually the account password, at the moment if there is a passphrase on the key we automatically ask for it. Specifying --passwd basically tells efs2 to not use a key.

**Comment by madflojo** [comment]
I see where the problem is now... The phrasing when it asks for the password is the same as the SSH Key Passphrase... silly me...

**Comment by paul-hammant** [comment]
Hmm, I was trying it with the dietpi thing I was playing with, and it objected. 

efs2 -u=root --password=dietpi 192.168.0.123

I assumed it wasn't what I though cos straight ssh root@192.168.0.123 worked fine. I wonder whether it was that dropbear SSH rather than openSSH thing again.

**Comment by paul-hammant** [comment]
OK, cool. Leaving it to you sir...

**Comment by madflojo** [comment]
@paul-hammant it won't accept a pass on the command line it will ask you for a password. Can you give it a try with the latest? it should go something like

```console
$ efs2 -u=root --passwd 192.168.0.123
Enter Password for root:
```

**Comment by paul-hammant** [comment]
Yup, is working now, quick turn around :)

**Comment by madflojo** [comment]
You caught me while I was online and it’s an easy one. :)
