### ISSUE TITLE
Document RUN SCRIPT

### ISSUE THREAD

**Issue by haary** [madflojo/efs2#19]
## Describe the idea

After I discovered efs2 shortly I wondered how one could execute arbitrary scripts or programs remotely. Sure you, can 

PUT script.sh /tmp/script.sh 0700
RUN /tmp/script.sh; rm /tmp/script.sh

But that seemed not very userfriendly to me.

Then I discovered in that there were once RUN CMD and RUN SCRIPT commands. Now there is only RUN (which is the same as RUN CMD I think).  RUN SCRIPT is still there, but undocumented.

### Describe possible implementations

Keep RUN SCRIPT and document it. 

Suggested Improvement: For security reasons mktemp(1) should be used to create the temporary script on the target.

**Comment by madflojo** [comment]
So guess I need to think about keeping RUN SCRIPT vs the PUT and RUN method. Which was also suggested by a user. I kind of like having a single word instruction personally.

On the comment around `mktemp` we are already generating a temp file name, is there something else you think we should be doing?

https://github.com/madflojo/efs2/blob/main/parser/parser.go#L98

**Comment by haary** [comment]
I see - I was under the impression that the created temporary file name is the same as the local file name, but this was obviously wrong.

**Comment by madflojo** [comment]
Cool no problem, wanted to make sure there wasn’t something I was missing.
