### ISSUE TITLE
put file error with permission deny

### ISSUE THREAD

**Issue by fujohnwang** [madflojo/efs2#4]
![image](https://user-images.githubusercontent.com/451506/37389469-7d3821be-279f-11e8-9cfd-777839759f81.png)

so, if not root user, how to offer authentication info to efs2 so that it can copy the file to root permission folders?

run sudo is not an option, I think

**Comment by madflojo** [comment]
As long as it was password less sudo you could put sudo in `RUN CMD sudo whoami` but that doesn't apply to the file uploads.

I'll have to think of a good way to implement this. I believe the way Ansible for example solves this is if a privilege escalation tool is configured (i.e. sudo). They just wrap the commands with `sudo` in front (which you can do as shown above). But for file uploads I believe they upload the file into `/tmp` as a temporary file and then move it.

You could in theory accomplish the same thing with the below.

```sh
PUT daemon.json /var/tmp/daemon.json 0644
RUN CMD sudo mv /var/tmp/daemon.json /etc/docker/daemon.json
```

But I'll try to think of a good way to implement this within `efs2`. I would certainly end up being a "use privilege escalation tool" flag to enable it.

**Comment by fujohnwang** [comment]
that's cool, man

I *like* efs2 so much. 

If I would like to design such a tool, it should be like this: Simple API for users , just RUN and PUT is a good choice.

**Comment by madflojo** [comment]
Awesome, thanks for that feedback!

**Comment by fujohnwang** [comment]
I make this work by setting server sudoers to be NOPASSWD, then when I run sudo , no password needed.  After that I can PUT file to somewhere I can put it to then `sudo mv` it.

**Comment by madflojo** [comment]
After thinking about this some more this can all be done with a combination of PUT and RUN commands along with the use of sudo. Right now Efs2 isn't aware of the target OS type but to support this it would need to be which somewhat makes it more complex. I'm going to close this but won't say there isn't the possibility of doing something like this in the future.
