### ISSUE TITLE
why don't make RUN CMD and RUN SCRIPT just be RUN?

### ISSUE THREAD

**Issue by fujohnwang** [madflojo/efs2#6]
say, the following works:

`RUN CMD cd elasticsearch-6.2.3 && sudo sysctl -w vm.max_map_count=262144`

but this will NOT:

`RUN CMD cd elasticsearch-6.2.3 && ./bin/elasticsearch -d -p pid` or `RUN CMD cd elasticsearch-6.2.3 && ./bin/elasticsearch -d -p pid`

but it's a common sense to combine and run like this.

we can parse this line and send to server, I don't think this is difficult, but I am not a gopher so I can't make my hand dirty, hope this can be done in the near future. 

：）

**Comment by madflojo** [comment]
Are you saying that in the example your thinking we should identify that `./bin/elasticsearch` is a script and we should copy it and send it over then run?

**Comment by fujohnwang** [comment]
No， not exactly, what I try to say is 2 point:

1. for a better UX, if we can use one instruction, say RUN instead of two: RUN CMD or RUN SCRIPT, then for users, this tool will be accepted much easier;
2. script is on server side already, but as the user, I don't care what's command on server or script on server, if the script is not on server, I can `PUT file server/file mode` with efs2, I just want `RUN cmd; cmd2; script1; etc... `

do I make it clear? ;0)

**Comment by madflojo** [comment]
Ah so you mean like removing the SCRIPT function all together.

**Comment by fujohnwang** [comment]
CMD or SCRIPT should be implementation details, not a User interface thing, I think.
